export const coins = [
    "Bitcoin",
    "Ethereum",
    "Tether USD",
    "USDC",
    "BNB",
    "XRP",
    "Binance USD",
    "Cardano",
    "Dogecoin",
    "OKB",
    "Solana",
    "Polygon",
    "Polkadot",
    "Shiba Inu",
    "Chainlink",
    "Wrapped Ether",
    "Litecoin",
    "TRON",
    "Uniswap",
    "Dai",
    "Avalanche",
    "Wrapped BTC",
    "Cosmos",
    "Toncoin",
    "Monero",
    "Ethereum Classic",
    "Lido DAO Token",
    "Huobi Token",
    "Bitcoin Cash",
    "Frax Share",
    "Trust Wallet Token",
    "Stellar",
    "Algorand",
    "Hedera",
    "Aptos",
    "Filecoin",
    "The Sandbox",
    "Wrapped liquid staked Ether 2.0",
    "Decentraland",
    "Internet Computer (DFINITY)",
    "NEAR Protocol",
    "VeChain",
    "EnergySwap",
    "Frax",
    "Quant",
    "PancakeSwap",
    "Immutable X",
    "Cronos",
    "Aave",
    "Terra Classic",
    "Flow",
    "EOS",
    "Elrond",
    "Theta Token",
    "Chiliz",
    "Tezos",
    "Pax Dollar",
    "Paxos Standard",
    "Bitcoin SV",
    "SUSHI",
    "Synthetix Network",
    "Zcash",
    "Curve DAO Token",
    "ApeCoin",
    "FTX Token",
    "WOO Network",
    "USDD",
    "Maker",
    "BitTorrent-New",
    "IOTA",
    "Fantom",
    "KuCoin Token",
    "Ravencoin",
    "Axie Infinity",
    "GateToken",
    "eCash",
    "Dash",
    "NEO",
    "Tokenize Xchange",
    "WEMIX TOKEN",
    "OEC Token",
    "Bloktopia",
    "Nexo",
    "THORChain",
    "PAX Gold",
    "TrueUSD",
    "Klaytn",
    "BinaryX",
    "Optimism",
    "Ankr",
    "Compound Ether",
    "Compound Dai",
    "Zilliqa",
    "APENFT",
    "Osmosis",
    "Mina Protocol Token",
    "Vulcan Forged",
    "Celsius Network",
    "Baby Doge Coin",
    "Arweave",
];
